### ISSUE TITLE
Enhance UI/UX of Sticky Notes

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/Sticky-Memo#1]
We want to improve the entire application's user interface and user experience to make them more visually appealing and user-friendly. This is a great opportunity for beginners to get hands-on experience with React and CSS.

Task:

1. Improve the design of the sticky notes (e.g., adding shadows, rounded corners, better color schemes).
2. Add a feature to change the color of sticky notes.
3. Ensure the sticky notes are responsive and look good on different screen sizes.

**Comment by Bicheka** [comment]
@narainkarthikv I will help you out

**Comment by Bicheka** [comment]
@narainkarthikv check the pr

**Comment by narainkarthikv** [comment]
Hi Bicheka, Once after working with the files don't forget to add your name to Contributors.md

**Comment by narainkarthikv** [comment]
Hi @Bicheka , I can handle the fonts and navbar styling. Can you help with updating the table component UI?

Tasks:

1. Add the Title and description at the end of the table, similar to a button.
2. Implement a search query feature within the table component.

**Comment by Bicheka** [comment]
@narainkarthikv be more specific because each row has its own title so I don't clearly understand the task

**Comment by narainkarthikv** [comment]
@Bicheka. As given in the exercise table (Picture 1), I want the addition of title and description to be at end of table in Sticky Memo Application. Can you help me with it?

Picture 1:
![Screenshot 2024-07-23 230604](https://github.com/user-attachments/assets/e217b3e1-055c-4e60-922b-d6882407b7a2)

Picture 2:
![Screenshot 2024-07-23 230906](https://github.com/user-attachments/assets/59fd5e09-29da-4ae5-9388-aab524866719)

**Comment by Bicheka** [comment]
I undestand, so you want to move that functionality bellow the table. Got it.

**Comment by Bicheka** [comment]
If you check the pr you will see that I moved the component that adds a new row to the table bellow. But that creates another issue where the form component that creates new rows stays bellow the last element of the table so if the table is very long eg 10,000 elements you will have to scroll to much to be able to add another one as shown in the image. I could fix by alowing the user to scroll through the list of table rows but to leave the add component fixed. Let me know if I was clear in my explanation.
![Uploading Screenshot 2024-07-23 at 2.25.48 PM.png…]()

**Comment by narainkarthikv** [comment]
@Bicheka, I see the issue. Could you ensure that the `createRow` component is fixed at the bottom of the container (so that once it reaches the footer of the monitor screen, the table should overflow along the y-axis)? This should help resolve the problem.

As I need some major tweaks in the application. I am looking for contributors who can contribute more and I can assign to some of the issues as below I have already raised.

1. A significant update to the entire application? This should include adding search filtration and implementing global state management for notes, boards, and tables since they share the same details (title, content). 
2. The state should be stored in local storage.

**Comment by Pcracker541** [comment]
💜💚

**Comment by Pcracker541** [comment]
💚💜
