### ISSUE TITLE
Notes go off-screen on small screens

### ISSUE THREAD

**Issue by dalekvim** [narainkarthikv/Sticky-Memo#16]
On small screens, notes appear to go off-screen to the right:
![image](https://github.com/user-attachments/assets/cec05ea9-a1af-4f8f-a1f9-1ed37aae9ce2)
This is a serious bug that may affect the usability of this application for mobile users.

**Comment by narainkarthikv** [comment]
As mentioned in #15, several UI tweaks should be made for Sticky-Memo. Thanks for noticing this and informing me.
