### ISSUE TITLE
Feat(MUI): Migrate from Regular CSS to MUI

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/sticky-memo#60]
1. **Set Up Material-UI:**
   - [x] Install Material-UI core and icons packages.
   - [x] Set up the MUI theme provider in the main application component.
   - [x] Create a custom theme to match the existing design language (colors, typography, etc.).

2. **Identify Components:**
   - [x] List all components currently styled with regular CSS.
   - [x] Review and document the purpose and usage of each component.

3. **Component Migration:**
   - [x] Convert each component to use MUI components and styling. 
     - For example:
       - Replace `<div>` with `<Box>` or `<Grid>` for layout.
       - Use MUI buttons, text fields, and other components where applicable.
   - [x] Ensure that the functionality of each component remains intact after the migration.
   - [x] Test components for responsiveness and consistency with the existing design.

4. **Update Styles:**
   - [x] Remove any existing CSS files related to the components being migrated.
   - [x] Replace custom styles with MUI's styling solutions (e.g., `sx` prop, `makeStyles`, or styled components).

5. **Documentation:**
   - [x] Update project documentation to reflect changes in styling practices and usage of Material-UI components.
   - [x] Create a guide for future developers on how to use MUI components in the project.

**Comment by ypoleto** [comment]
Hey, can I work on this issue?

**Comment by ypoleto** [comment]
Hey! Can I work on this issue?

**Comment by narainkarthikv** [comment]
Hi @ypoleto, 

I've assigned this issue to you. When you're done checking that all the functionalities are working as expected, please go ahead and create a PR.

Thanks!
